### ISSUE TITLE
Check if eventDate changes impact PyGBIF

### ISSUE THREAD

**Issue by MattBlissett** [gbif/pygbif#118]
See https://github.com/gbif/gbif-api/issues/4#issuecomment-1385497157 for the proposed change, and https://www.gbif-uat.org/occurrence/search?dataset_key=d6167827-973d-429a-a00c-8ea294d62d80 (or [API](https://api.gbif-uat.org/v1/occurrence/search?dataset_key=d6167827-973d-429a-a00c-8ea294d62d80) for some example data.

**Comment by CecSve** [comment]
Search and download tested for the following dataset: https://www.gbif.org/dataset/84ede380-f762-11e1-a439-00145eb45e9a. Event dates are displayed as intended.
