### ISSUE TITLE
Readthedocs maintainers

### ISSUE THREAD

**Issue by sckott** [gbif/pygbif#119]
https://pygbif.readthedocs.io/en/latest/

I'm still the only admin on the readthedocs project for pygbif. Which emails can I add for the current maintainers to that readthedocs project? I don't know but I might be able to transfer to you after I add your emails. 

p.s. i think some infra needs to be updated for pygbif on readthedocs https://blog.readthedocs.com/migrate-configuration-v2/ - which would be ideal for current maintainers to do and not me 😺

**Comment by MattBlissett** [comment]
Hi Scott,

Thanks for the prompt.  Could you add systems@gbif.org, and then I can add other staff as necessary?

**Comment by sckott** [comment]
Great, thanks. It says that email does not exist, so I'm guessing you have to sign up for an account there first, https://readthedocs.org/accounts/signup/ - and then I can add that email as a maintainer

**Comment by MattBlissett** [comment]
Thanks, I have signed up, would you try again?

**Comment by sckott** [comment]
Thanks, done.
