### ISSUE TITLE
Download with taxonKey produces 401 check your number of active downloads.

### ISSUE THREAD

**Issue by sparkvilla** [gbif/pygbif#120]
I am trying to use the occ.download method to download data with a specific taxonKey. Here is the snippet:

```
key = species.name_backbone(references[1])["usageKey"]
# It returns a key -> 3992587

res = occ.download('taxonKey = 3992587')
# This produces -> *** Exception: error: , with error status code 401check your number of active downloads.
```
I am not sure what it is causing the error. I just created an account on GBIF. I also made sure that the required env variables are set in my env. Any help? 

python version = 3.10.12
pygbif version = 0.6.3

**Comment by sparkvilla** [comment]
I am sorry. I just found out that the credentials in the env file where misspelled. That was the problem. You can close the issue. Thanks anyway

**Comment by ManonGros** [comment]
Thanks for letting us know @sparkvilla
