### ISSUE TITLE
ImportError: cannot import name 'remove_expired_responses' from 'requests_cache'

### ISSUE THREAD

**Issue by akuehn007** [gbif/pygbif#130]
I'm using Python 3 (ipykernel) on jupyterhub, and the issue is with importing pygbif, whichever version it's trying to import.
As the title suggests, when I use `import pygbif` it returns the given error:
`ImportError: cannot import name 'remove_expired_responses' from 'requests_cache'`
According to the `requests-cache` current version history, `remove_expired_responses` has deprecated and been fully removed as of the most recent update.
If I'm reading the changelog correctly, the replacement module is `BaseCache.delete(expired=True)`
Thanks for your hard work.

**Comment by CecSve** [comment]
Thank you for reporting the issue - we have fixed this in https://github.com/gbif/pygbif/commit/bc4d8faa47eeba5681cedb4bf828e3551f685eb7 and the change will be part of the next release. Until then, please use the dev version.
