### ISSUE TITLE
can't use caching:   AttributeError: module 'requests_cache' has no attribute 'delete'

### ISSUE THREAD

**Issue by abubelinha** [gbif/pygbif#145]
Python 3.8.7, pygbif 0.6.4:
```
Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygbif
>>> pygbif.__version__
'0.6.4'
>>> pygbif.caching(True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\\Python38\lib\site-packages\pygbif\caching.py", line 86, in caching
    requests_cache.delete(expired=True)
AttributeError: module 'requests_cache' has no attribute 'delete'
```
I saw some other issues about requests_cache and they are closed, so I understand they have been solved.
But I think my pygbif version is the most recent available.
Any ideas?

**Comment by abubelinha** [comment]
For now I downgraded to pygbif 0.6.3 and my above lines do not raise any errors.

I think this was the origin of the problem because it introduced the above error line 86:
https://github.com/gbif/pygbif/pull/127

`requests_cache.delete(expired=True)`

**Comment by jhnwllr** [comment]
@abubelinha Can I ask what version of the `requests_cache` library you are using? 

We might need to update the minimum version in `requirements.txt`. 

I am using `requests_cache` `1.2.0`. 

And I don't get any error on import.

**Comment by abubelinha** [comment]
```
>>> import requests_cache
>>> requests_cache.__version__
'1.0.0'

```

**Comment by jhnwllr** [comment]
I can reproduce the error when I downgrade `requests_cache` enough

```python
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygbif        
>>> pygbif.__version__
'0.6.4'
>>> pygbif.caching(True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ftw712\Desktop\packages\pygbif\pygbif\caching.py", line 86, in caching
    requests_cache.delete(expired=True)
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'requests_cache' has no attribute 'delete'
>>> import requests_cache 
>>> requests_cache.__version__ 
'0.7.0'
>>>
```

**Comment by lucbettaieb** [comment]
Can this be fixed by updating the `requirements.txt` line for `requests-cache` to then be `>=1.2.0`?

Would be an easy fix, then.

**Comment by abubelinha** [comment]
Thanks @CecSve , @jhnwllr and @lucbettaieb 
- I upgraded `requests_cache` to 1.2.0.
- Then I upgraded `pygbif` to 0.6.4

Now I can call `pygbif.caching(True)` and "it works", since there is no error message. 

But caching is proving to be useless for my use case (see #146).
