### ISSUE TITLE
Update to requirements.txt file

### ISSUE THREAD

**Issue by CecSve** [gbif/pygbif#147]
Update the [requirements.txt](https://github.com/gbif/pygbif/blob/master/requirements.txt) line for requests-cache to be >=1.2.0 as suggested [here](https://github.com/gbif/pygbif/issues/145#issuecomment-2088430236)

**Comment by jhnwllr** [comment]
I found that `requests-cache>=1.0.0` works, so I don't think I will force people to update to the latest version just to `1.0.0`
