### ISSUE TITLE
Migrate project to GBIF repository

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pygbif#85]
As requested by @sckott - please assign it to me as confirmation and I will move it to github.com/gbif.

**Comment by timrobertson100** [comment]
Actually, I think you can initiate the transfer.
Settings / danger zone / transfer and enter "GBIF" at the target.

Can you please try that?

**Comment by MattBlissett** [comment]
I think Scott is right, a transfer can be requested from his account to yours, but he can't request a transfer to GBIF's account — and he can't give either of us admin access on his repository.

https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/transferring-a-repository#transferring-a-repository-owned-by-your-user-account

**Comment by sckott** [comment]
I'll try transferring to Tim

**Comment by timrobertson100** [comment]
Thanks, @sckott - I received it, and moved to https://github.com/gbif/pygbif 

All the best

**Comment by sckott** [comment]
Great, glad it worked.
